### ISSUE TITLE
Сompilation error due to tabs

### ISSUE THREAD

**Issue by snxx-lppxx** [toitlang/toit#407] opened 2022-02-02 16:55 UTC
```sh
$ toit run --no-device main.toit
# main.toit:2:1: error: Can't have tabs in leading whitespace
#        print "Hello, world!"
# ^
# Compilation failed.
```

---

```sh
$ toit version
# +---------+------------+
# | VERSION |    DATE    |
# +---------+------------+
# | v1.16.0 | 2021-11-18 |
# +---------+------------+
```

**Comment by snxx-lppxx** [comment] 2022-02-02 17:16
Hi @hoegge, I didn't claim anything. I deliberately used tabulation. The program doesn't compile when using tabs.

**Comment by hoegge** [comment] 2022-02-02 17:50
Ok. Guess that is just by design, that indentation must be space and not tab, although not clearly described in https://docs.toit.io/language/syntax

**Comment by floitsch** [comment] 2022-02-02 17:56
I just released a new version of the docs that makes it more explicit that tabs aren't allowed.
The new doc should be live soon. Closing already now.

**Closed by floitsch** 2022-02-02 17:56 UTC
